### ISSUE TITLE
No data on graphs

### ISSUE THREAD

**Issue by celavek** [vpenso/prometheus-slurm-exporter#6]
Hi,

I have installed prometheus-slurm-exporter as a service - I have grafana, prometheus running as services also. I have configured the Prometheus data source correctly in Grafana(tested and working) and added the recommended configuration to the prometheus.yml. Unfortunately the graphs in the dashboards report "No data points". Do I need to make any other configurations in order for this to work? Have you seen this type of behavior - any hints would be very much welcomed.

Thank you

![grafana_slurm_2](https://user-images.githubusercontent.com/1454988/45619844-13290800-ba7b-11e8-8521-09c23a5cf548.png)
![grafana_slurm_1](https://user-images.githubusercontent.com/1454988/45619845-13290800-ba7b-11e8-8400-b1c5fa560500.png)

**Comment by mtds** [comment]
Hi.

The only reason why you don't see anything is because the exporter is not outputting
any data.

1. Where is the exporter running? Is it installed on the same machine where the Slurm
master is running? Or is it installed somewhere else? In the last case, are there any
firewall in the middle?

2. Have you tried to manually execute the commands inside the GOlang modules?
For example: in order to get the status of the Slurm queues, the exporter executes
internally the following command: `/usr/bin/squeue -h -o %A,%T`
In order to get the status of the nodes, the following command is executed:
`sinfo -h -o %n,%T`

Note that you should try to execute the queries on point **2** with the same user 
that launched the exporter (just to exclude permission problems). 

If the above two queries did not report any data or throws out an error, then you
should fix your Slurm master (or the communication with it) before thinking about 
the exporter itself.

**Comment by celavek** [comment]
Hi,

Thank you for the hints.

1. All the services including the slurm master are running on the same machine. No firewall involved.
2. I have ran the commands as the user that starts and controls the prometheus services. I have the expected output:

```
root@zalmoxis ~/work
#sudo -H -u prometheus groups                                                                                            
prometheus cluster

root@zalmoxis ~/work
#sudo -H -u prometheus sinfo -h -o %n,%T
cn_burebista,mixed

root@zalmoxis ~/work
#sudo -H -u prometheus squeue -h -o %A,%T    
8760,PENDING
8761,PENDING
8762,PENDING
8763,PENDING
8764,PENDING
8765,PENDING
8766,PENDING
8767,PENDING
8768,PENDING
8769,PENDING
8770,PENDING
8771,PENDING
8772,PENDING
8773,PENDING
```

**Comment by mtds** [comment]
Hi.

Ok, so it looks like the problem is not with the Slurm master.

Moving on, the next thing you can check is to poll the exporter directly from the command line
(via cURL) and verify the metrics extracted:

`curl -s http://localhost:8080/metrics | grep -v ^# | grep slurm`

In this case, there's no obligation to use the same userid used by the exporter: root or any
other user on the host should be fine.

The command should report a similar output (the numbers will be different, of course, since
they depend on the size of your cluster):

```bash
slurm_nodes_alloc 487
slurm_nodes_comp 0
slurm_nodes_down 67
slurm_nodes_drain 0
slurm_nodes_err 0
slurm_nodes_fail 0
slurm_nodes_idle 83
slurm_nodes_maint 0
slurm_nodes_mix 118
slurm_nodes_resv 0
slurm_queue_cancelled 0
slurm_queue_completed 0
slurm_queue_completing 1
slurm_queue_configuring 0
slurm_queue_failed 0
slurm_queue_node_fail 0
slurm_queue_pending 60
slurm_queue_preempted 0
slurm_queue_running 9106
slurm_queue_suspended 1
slurm_queue_timeout 0
slurm_scheduler_backfill_depth_mean 1263
slurm_scheduler_backfill_last_cycle 1.987734e+06
slurm_scheduler_backfill_mean_cycle 563938
slurm_scheduler_cycle_per_minute 29
slurm_scheduler_last_cycle 8452
slurm_scheduler_mean_cycle 18006
slurm_scheduler_queue_size 0
slurm_scheduler_threads 10
```

If you get the output, it means something went wrong within the polling process from Prometheus
itself. In this case, the second step would be to connect to Prometheus through its web interface
('expression browser') which usually is available on port **9090**: `http://localhost:9090/graph`

On the search bar, you can just input one of the metrics extracted by the Slurm exporter
(e.g. slurm_nodes_idle) and check if you get the same number you have got from the  
command line. If it's the case, then the problem is in the communication between Grafana
and Prometheus and you should check the settings of your Grafana dashboard for Slurm.

**Comment by celavek** [comment]
Hi,

Thank you for the help! I managed to make it work.

It was related to the last issue you mentioned - that is a problem between prometheus and the slurm exporter. I misconfigured the slurm exporter target, because I copied it verbatim from your configuration example `- targets: ['slurm_host.fqdn:8080']`, failing to see that I should put my own hostname there. I have now the basic info on the graphs - picture attached. Just as a side note if you look at the picture, why do I have the total nodes at 1(very, very small cluster I know) but it is not shown as idle, allocated or completed although jobs are running on it?

![grafana_slurm_3](https://user-images.githubusercontent.com/1454988/45689878-5eafe480-bb55-11e8-964f-226d1600785f.png)


Once again thank you for the support!
